language: python
matrix:
    include:
        -   env: TOXENV=py27
        -   env: TOXENV=py34
            python: 3.4
        -   env: TOXENV=py35
            python: 3.5
        -   env: TOXENV=pypy
            python: pypy
        -   env: TOXENV=pypy3
            python: pypy3
install: pip install tox coveralls
script: tox
sudo: false
after_success: coveralls
